### ISSUE TITLE
[expo] Cause: Unable to find a specification for `v8-ios` depended upon by `RNV8`

### ISSUE THREAD

**Issue by matt-42** [Kudo/react-native-v8#180] opened 2023-06-27 21:17 UTC
How can we use react-native-v8 only on android and NOT in ios with expo ?
I specified ` ["react-native-v8", {"android": true, "ios": false}]` in app.json but prebuild failed to generate the ios directory:
```


✔ Would you like to proceed? … yes

✔ Cleared android, ios code
✔ Created native projects | gitignore skipped
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using npm
> npm install
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
✔ Config synced
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a specification for `v8-ios` depended upon by `RNV8`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by Kudo** [comment] 2023-07-03 00:33
thanks!. the issue is fixed by #184 and published in `react-native-v8@2.2.0`.

**Closed by Kudo** 2023-07-03 00:33 UTC
