### ISSUE TITLE
Upgrading to 0.59.10-patch.3 crashes app

### ISSUE THREAD

**Issue by coderdave** [Kudo/react-native-v8#30] opened 2019-11-05 23:05 UTC
I wish I got better errors as to why it's crashing. It just says "[app] has stopped".

It was working fine with patch 0 but now I can't go back to that. I think it has something to do with 
v8-android upgrading to 7.8.0?

**Comment by Kudo** [comment] 2019-11-06 06:10
I am sorry to introduce breaking change, please try to upgrade react-native-v8 as well.

Breaking Changes

Since V8 did change their embedder API interface, original react-native-v8 will access to non existing symbol and crash.
Please upgrade react-native-v8 to one of these version.

v0.59.10-patch.3
v0.60.6-patch.1
v0.61.1-patch.2
v0.61.2-patch.0
v0.61.3-patch.0
v0.61.4-patch.0

**Comment by bhaskarGyan** [comment] 2019-11-06 06:11
I am also facing the same issue, with v8-android 7.8.0, the app is crashing on startup but with 7.5.1 is working fine. All the other dependencies remain the same.

(https://github.com/Kudo/v8-android-buildscripts/issues/2)

**Comment by Kudo** [comment] 2019-11-06 09:42
Please let me know if the new react-native-v8 version did fix the crash issue for you. Thanks.

**Comment by wv1124** [comment] 2019-11-06 12:19
make sure:
"react-native-v8": "0.59.10-patch.3", => "v8-android@7.8.0",
"react-native-v8": "0.59.10-patch.2", => "v8-android@7.5.1",

"react-native-v8": "0.59.10-patch.2", => "v8-android@7.8.0", crash

**Comment by bhaskarGyan** [comment] 2019-11-07 02:35
@Kudo , I can confirm it is working with v0.60.6-patch.1

**Comment by Kudo** [comment] 2019-11-07 11:34
@bhaskarGyan Thanks for your confirmation.

Sorry to all that I was introducing yet another breaking change for #29 
If you upgrade to v8-android 7.8.1,
please use any of these versions:

- v0.59.10-patch.4
- v0.60.6-patch.2
- v0.61.1-patch.3
- v0.61.2-patch.1
- v0.61.3-patch.1
- v0.61.4-patch.1

**Comment by Kudo** [comment] 2019-11-29 00:39
I am going to close this issue.
Please feel free to let me know if there are any problems. Thank you.

**Closed by Kudo** 2019-11-29 00:39 UTC
